[project]
channels = ["conda-forge"]
name = "NUH"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
streamlit = ">=1.44.0,<2"
pandas = ">=2.2.3,<3"
hydrofunctions = ">=0.2.4,<0.3"
scipy = ">=1.13.1,<2"
matplotlib = ">=3.9.4,<4"
plotly = ">=6.0.1,<7"
numpy = ">=2.0.2,<3"